name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install

    - name: PrismaORM
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pnpm -F db prisma generate && pnpm -F db prisma generate --sql
