name: "Setup and install"
description: "Common setup steps for Actions"

inputs:
  prisma-generate:
    description: "Whether to generate Prisma client and SQL files"
    required: false
    default: "false"
  database-url:
    description: "The URL of the database"
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install

    - shell: bash
      if: inputs.prisma-generate == 'true'
      env:
        DATABASE_URL: ${{ inputs.database-url }}
      run: pnpm -F db prisma generate && pnpm -F db prisma generate --sql
