import type { Languages } from "@prisma/client";

const languageCodeToCountryCode = (languageCode: Languages) => {
  switch (languageCode) {
    case "ab":
      return "ru";
    case "aa":
      return "";
    case "af":
      return "";
    case "ak":
      return "";
    case "sq":
      return "";
    case "am":
      return "";
    case "ar":
      return "sa";
    case "an":
      return "";
    case "hy":
      return "";
    case "as":
      return "";
    case "av":
      return "";
    case "ae":
      return "";
    case "ay":
      return "";
    case "az":
      return "";
    case "bm":
      return "";
    case "ba":
      return "";
    case "eu":
      return "";
    case "be":
      return "";
    case "bn":
      return "";
    case "bi":
      return "";
    case "bs":
      return "";
    case "br":
      return "";
    case "bg":
      return "";
    case "my":
      return "";
    case "ca":
      return "";
    case "ch":
      return "";
    case "ce":
      return "";
    case "ny":
      return "";
    case "cu":
      return "";
    case "cv":
      return "";
    case "kw":
      return "";
    case "co":
      return "";
    case "cr":
      return "";
    case "hr":
      return "";
    case "cs":
      return "cz";
    case "da":
      return "";
    case "dv":
      return "";
    case "nl":
      return "";
    case "dz":
      return "";
    case "en":
      return "us";
    case "eo":
      return "";
    case "et":
      return "";
    case "ee":
      return "";
    case "fo":
      return "";
    case "fj":
      return "";
    case "fi":
      return "";
    case "fr":
      return "fr";
    case "fy":
      return "";
    case "ff":
      return "";
    case "gd":
      return "";
    case "gl":
      return "";
    case "lg":
      return "";
    case "ka":
      return "";
    case "de":
      return "de";
    case "el":
      return "";
    case "kl":
      return "";
    case "gn":
      return "";
    case "gu":
      return "";
    case "ht":
      return "";
    case "ha":
      return "";
    case "he":
      return "";
    case "hz":
      return "";
    case "hi":
      return "in";
    case "ho":
      return "";
    case "hu":
      return "";
    case "is":
      return "";
    case "io":
      return "";
    case "ig":
      return "";
    case "id":
      return "";
    case "ia":
      return "";
    case "ie":
      return "";
    case "iu":
      return "";
    case "ik":
      return "";
    case "ga":
      return "";
    case "it":
      return "";
    case "jv":
      return "";
    case "kn":
      return "";
    case "kr":
      return "";
    case "ks":
      return "";
    case "kk":
      return "kz";
    case "km":
      return "";
    case "ki":
      return "";
    case "rw":
      return "";
    case "ky":
      return "";
    case "kv":
      return "";
    case "kg":
      return "";
    case "kj":
      return "";
    case "ku":
      return "";
    case "lo":
      return "";
    case "la":
      return "";
    case "lv":
      return "";
    case "li":
      return "";
    case "ln":
      return "";
    case "lt":
      return "lt";
    case "lu":
      return "";
    case "lb":
      return "";
    case "mk":
      return "";
    case "mg":
      return "";
    case "ms":
      return "";
    case "ml":
      return "";
    case "mt":
      return "";
    case "gv":
      return "";
    case "mi":
      return "";
    case "mr":
      return "";
    case "mh":
      return "";
    case "mn":
      return "mn";
    case "na":
      return "";
    case "nv":
      return "";
    case "nd":
      return "";
    case "nr":
      return "";
    case "ng":
      return "";
    case "ne":
      return "np";
    case "no":
      return "";
    case "nb":
      return "";
    case "nn":
      return "";
    case "ii":
      return "";
    case "oc":
      return "";
    case "oj":
      return "";
    case "or":
      return "";
    case "om":
      return "";
    case "os":
      return "";
    case "pi":
      return "";
    case "ps":
      return "";
    case "fa":
      return "ir";
    case "pl":
      return "pl";
    case "pa":
      return "";
    case "qu":
      return "";
    case "ro":
      return "";
    case "rm":
      return "";
    case "rn":
      return "";
    case "ru":
      return "ru";
    case "se":
      return "";
    case "sm":
      return "";
    case "sg":
      return "";
    case "sa":
      return "";
    case "sc":
      return "";
    case "sr":
      return "";
    case "sn":
      return "";
    case "sd":
      return "";
    case "si":
      return "";
    case "sk":
      return "";
    case "sl":
      return "";
    case "so":
      return "";
    case "st":
      return "";
    case "su":
      return "";
    case "sw":
      return "";
    case "ss":
      return "";
    case "sv":
      return "se";
    case "tl":
      return "";
    case "ty":
      return "";
    case "tg":
      return "";
    case "ta":
      return "";
    case "tt":
      return "";
    case "te":
      return "";
    case "th":
      return "";
    case "bo":
      return "";
    case "ti":
      return "";
    case "to":
      return "";
    case "ts":
      return "";
    case "tn":
      return "";
    case "tr":
      return "tr";
    case "tk":
      return "";
    case "tw":
      return "";
    case "ug":
      return "";
    case "uk":
      return "ua";
    case "ur":
      return "";
    case "uz":
      return "";
    case "ve":
      return "za";
    case "vi":
      return "vn";
    case "vo":
      return "de";
    case "wa":
      return "";
    case "cy":
      return "gb-wls";
    case "wo":
      return "";
    case "xh":
      return "";
    case "yi":
      return "";
    case "yo":
      return "";
    case "za":
      return "";
    case "zu":
      return "ls";

    case "es":
      return "es";
    case "es_la":
      return "mx";

    case "pt_br":
      return "br";
    case "pt_pt":
      return "pt";

    case "ja":
      return "jp";
    case "ja_ro":
      return "jp";

    case "ko":
      return "kr";
    case "ko_ro":
      return "kr";

    case "zh":
      return "cn";
    case "zh_hk":
      return "cn";
  }
};

export const LanguageUtils = {
  languageCodeToCountryCode,
};
