FROM node:21.7.3-alpine
WORKDIR /home/app

ARG SKIP_ENV_VALIDATION=true
ENV SKIP_ENV_VALIDATION=true

# Database
ARG DIRECT_DATABASE_URL=${DIRECT_DATABASE_URL}
ENV DATABASE_URL=${DIRECT_DATABASE_URL}

# CDN
ARG NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
ENV NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}

# image-orchestrator API
ARG NEXT_PUBLIC_IO_URL=${NEXT_PUBLIC_IO_URL}
ENV NEXT_PUBLIC_IO_URL=${NEXT_PUBLIC_IO_URL}

# Meilisearch
ARG NEXT_PUBLIC_MEILISEARCH_URL=${NEXT_PUBLIC_MEILISEARCH_URL}
ENV NEXT_PUBLIC_MEILISEARCH_URL=${NEXT_PUBLIC_MEILISEARCH_URL}

ARG NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY=${NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY}
ENV NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY=${NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY}

COPY package.json .
COPY package-lock.json .
COPY prisma/ .

RUN npm i
RUN npm run db:migrate deploy

COPY . .

RUN npm run build
CMD npm start
