FROM node:21-alpine
WORKDIR /home/app

ARG SKIP_ENV_VALIDATION=true
ENV SKIP_ENV_VALIDATION=true

# CDN
ENV NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}

# image-orchestrator API
ENV NEXT_PUBLIC_IO_URL=${NEXT_PUBLIC_IO_URL}

# Meilisearch
ENV NEXT_PUBLIC_MEILISEARCH_URL=${NEXT_PUBLIC_MEILISEARCH_URL}
ENV NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY=${NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY}

# Soketi
ENV NEXT_PUBLIC_SOKETI_HOST=${NEXT_PUBLIC_SOKETI_HOST}
ENV NEXT_PUBLIC_SOKETI_PORT=${NEXT_PUBLIC_SOKETI_PORT}
ENV NEXT_PUBLIC_SOKETI_APP_KEY=${NEXT_PUBLIC_SOKETI_APP_KEY}

COPY package.json .
COPY package-lock.json .
COPY prisma/ .

RUN npm i

COPY . .

RUN npm run build
CMD npm start