services:
  postgres:
    image: "postgres:16-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "$DATABASE_PORT:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  meilisearch:
    image: "getmeili/meilisearch:v1.9"
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=$MEILISEARCH_MASTER_KEY
      - MEILI_ENV=$NODE_ENV
    ports:
      - "$MEILISEARCH_PORT:7700"
    volumes:
      - "./data/meilisearch:/meili_data"

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    restart: unless-stopped
    ulimits:
      memlock: -1
    ports:
      - "$DRAGONFLY_PORT:6379"
    volumes:
      - "./data/dragonfly:/data"

  clickhouse:
    image: "bitnami/clickhouse:24"
    restart: unless-stopped
    environment:
      - CLICKHOUSE_ADMIN_USER=$CLICKHOUSE_USERNAME
      - CLICKHOUSE_ADMIN_PASSWORD=$CLICKHOUSE_PASSWORD
    ports:
      - "$CLICKHOUSE_PORT:8123"
    volumes:
      - "./data/clickhouse:/bitnami/clickhouse"
      - "./packages/logs/config.xml:/bitnami/clickhouse/etc/conf.d/override.xml:ro"
