version: "3.8"
services:
  postgres:
    image: "postgres:16-alpine"
    restart: always
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "$DATABASE_PORT:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  meilisearch:
    image: "getmeili/meilisearch:v1.7"
    restart: always
    environment:
      - MEILI_MASTER_KEY=$MEILISEARCH_MASTER_KEY
      - MEILI_ENV=$NODE_ENV
    ports:
      - "$MEILISEARCH_PORT:7700"
    volumes:
      - "./data/meilisearch:/meili_data"

  soketi:
    image: "quay.io/soketi/soketi:1.6-16-debian"
    restart: always
    environment:
      - SOKETI_DEFAULT_APP_ID=$SOKETI_APP_ID
      - SOKETI_DEFAULT_APP_KEY=$NEXT_PUBLIC_SOKETI_APP_KEY
      - SOKETI_DEFAULT_APP_SECRET=$SOKETI_APP_SECRET
    ports:
      - "$NEXT_PUBLIC_SOKETI_PORT:6001"

  minio:
    image: minio/minio
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    volumes:
      - "./data/minio:/data"
