packages:
  - apps/*
  - packages/*
  - tooling/*

allowBuilds:
  esbuild: false
  protobufjs: false
  sharp: true

# minimumReleaseAge: 10080 # 7 days

minimumReleaseAgeExclude:
  - oxlint-tailwindcss@1.1.0
