name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Knip
        run: pnpm knip

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Check
        run: pnpm check:ws

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: PrismaORM
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm -F db prisma generate && pnpm -F db prisma generate --sql

      - name: Typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    needs: [knip, check, typecheck]
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Test
        run: pnpm test
