name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Knip
        run: pnpm knip

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Format
        run: pnpm format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Lint
        run: pnpm lint

      - name: Lint Workspace
        run: pnpm lint:ws

  unit-tests:
    runs-on: ubuntu-latest
    needs: [knip, format, lint]
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run Unit Tests
        run: pnpm test:unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: [knip, format, lint]
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run Integration Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm test:integration
